// <auto-generated />
namespace ReportManagement.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Broadcast_messagerename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Broadcast_messagerename));
        
        string IMigrationMetadata.Id
        {
            get { return "202003222326412_Broadcast_message rename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
